# Generated by Django 3.1.2 on 2020-10-07 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('berry', models.CharField(choices=[('O', 'Oran'), ('C', 'Chesto'), ('P', 'Pecha'), ('R', 'Rawst'), ('A', 'Aspear'), ('S', 'Sitrus')], default='O', max_length=1)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pokemon')),
            ],
        ),
    ]
